# Advanced optimization configuration
cxx_path: "/usr/local/llvm/bin/clang++"

optimization_passes:
  - mem2reg
  - sroa
  - instcombine
  - simplifycfg
  - reassociate
  - gvn
  - dce
  - adce
  - loop-unroll
  - licm

compiler_flags:
  - "-std=c++20"
  - "-Wall"
  - "-Wextra"
  - "-O0"  # Start with no optimization

linker_flags:
  - "-lm"
  - "-lpthread"
