# Incremental optimization configuration
# Start with O2 optimization and make some tweaks
base_optimization: "2"
incremental_changes:
  - "-loop-vectorize"    # Remove vectorization
  - "-slp-vectorizer"    # Remove SLP vectorization
  - "+aggressive-instcombine"  # Add aggressive instruction combining

compiler_flags:
  - "-std=c++20"
  - "-Wall"

linker_flags:
  - "-lm"
