# Size optimization with custom tweaks
base_optimization: "s"
incremental_changes: "+loop-unroll,-inline,+dce"  # Comma-separated string format

compiler_flags:
  - "-std=c++20"
  - "-Wall"
  - "-Os"  # This will be applied at compile time

linker_flags:
  - "-lm"
